# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Boxnotes2md < Formula
  desc "Convert Box Notes JSON files into GitHub Flavored Markdown."
  homepage "https://github.com/dayflower/boxnotes2md"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dayflower/boxnotes2md/releases/download/v0.1.1/boxnotes2md_Darwin_x86_64.tar.gz"
      sha256 "2dfd5066022f1dd1d89ffaaa0aee1bfe7154c78de7399ee0dc54b4714c93d7fa"

      def install
        bin.install "boxnotes2md"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dayflower/boxnotes2md/releases/download/v0.1.1/boxnotes2md_Darwin_arm64.tar.gz"
      sha256 "52e71b477f30d88fe03f45deb9c969a8c09810d7e7658fdfca0e94df85cd7680"

      def install
        bin.install "boxnotes2md"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dayflower/boxnotes2md/releases/download/v0.1.1/boxnotes2md_Linux_x86_64.tar.gz"
      sha256 "cd9264f0a1f4debab6605561937a2afe9f6936e4e7999ea96803bc3c15c740ea"
      def install
        bin.install "boxnotes2md"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dayflower/boxnotes2md/releases/download/v0.1.1/boxnotes2md_Linux_arm64.tar.gz"
      sha256 "69ea3ea5dd4eac915a5b4447d387613207d360a3ab9c5e69f06c2d2ec7b0460b"
      def install
        bin.install "boxnotes2md"
      end
    end
  end
end
