# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xcute < Formula
  desc "A CLI tool that executes commands with placeholders replaced by input from stdin"
  homepage "https://github.com/dayflower/xcute"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dayflower/xcute/releases/download/v0.1.0/xcute_Darwin_x86_64.tar.gz"
      sha256 "c9e310c38e49bd6b005a982dd0db122d5c5a9f841bd1666067e7abc125a86cc3"

      def install
        bin.install "xcute"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dayflower/xcute/releases/download/v0.1.0/xcute_Darwin_arm64.tar.gz"
      sha256 "85932cdc4fc48b20f74edd14666c41c2c0fb96af9c0889afa710c4a5d43c5a4b"

      def install
        bin.install "xcute"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dayflower/xcute/releases/download/v0.1.0/xcute_Linux_x86_64.tar.gz"
      sha256 "ffc077738e0f1bcc2ad20493ad1fc29d01b03f99d2bd49fdb739d83b73b248c7"
      def install
        bin.install "xcute"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dayflower/xcute/releases/download/v0.1.0/xcute_Linux_arm64.tar.gz"
      sha256 "459307523b8b85ac2f70b5d3804b42dfc7775389e2fbdc3c443a2e5eabef431f"
      def install
        bin.install "xcute"
      end
    end
  end

  test do
    system "#{bin}/xcute", "--help"
  end
end
