# This file was generated by GoReleaser. DO NOT EDIT.
cask "boxnotes2md" do
  name "boxnotes2md"
  desc "Convert Box Notes JSON files into GitHub Flavored Markdown."
  homepage "https://github.com/dayflower/boxnotes2md"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "boxnotes2md"

  on_macos do
    on_intel do
      url "https://github.com/dayflower/boxnotes2md/releases/download/v#{version}/boxnotes2md_Darwin_x86_64.tar.gz"
      sha256 "43f4d56fcdc08f3bcb454545fa95d478870bb824a82452f13e89dc53088358c6"
    end
    on_arm do
      url "https://github.com/dayflower/boxnotes2md/releases/download/v#{version}/boxnotes2md_Darwin_arm64.tar.gz"
      sha256 "297068d8794d14192ec88781168543fdb1b1756504c1a7f11341ac4b768cfda3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dayflower/boxnotes2md/releases/download/v#{version}/boxnotes2md_Linux_x86_64.tar.gz"
      sha256 "3e045a030a35db9bef22f08541a6a8ba5bfc75559f5a5f4c919d2578e5043b2b"
    end
    on_arm do
      url "https://github.com/dayflower/boxnotes2md/releases/download/v#{version}/boxnotes2md_Linux_arm64.tar.gz"
      sha256 "9532f8df788348f6060bcff29e01ee2e2b00075e0cfc82f65707bbfa50628bd6"
    end
  end

  # No zap stanza required
end
