# This file was generated by GoReleaser. DO NOT EDIT.
cask "boxnotes2md" do
  name "boxnotes2md"
  desc "Convert Box Notes JSON files into GitHub Flavored Markdown."
  homepage "https://github.com/dayflower/boxnotes2md"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "boxnotes2md"

  on_macos do
    on_intel do
      url "https://github.com/dayflower/boxnotes2md/releases/download/v#{version}/boxnotes2md_Darwin_x86_64.tar.gz"
      sha256 "92f59342eedf57a9dc54896dda1cfe9609cb4f787fe78e3f27f9033eabe49a86"
    end
    on_arm do
      url "https://github.com/dayflower/boxnotes2md/releases/download/v#{version}/boxnotes2md_Darwin_arm64.tar.gz"
      sha256 "671098de7755cf9ded946f11e790e6d4b2503942510c5efc4e06419abc043802"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dayflower/boxnotes2md/releases/download/v#{version}/boxnotes2md_Linux_x86_64.tar.gz"
      sha256 "b6296f95a2ea44ccbf91f3d092bfd2f25b0458e7413bad5020cbe3d1ff1c395d"
    end
    on_arm do
      url "https://github.com/dayflower/boxnotes2md/releases/download/v#{version}/boxnotes2md_Linux_arm64.tar.gz"
      sha256 "c71a43ccf5130dfced3d2e6f911579d92a209339ad0fbd057955985189749be2"
    end
  end

  # No zap stanza required
end
