# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Boxnotes2md < Formula
  desc "Convert Box Notes JSON files into GitHub Flavored Markdown."
  homepage "https://github.com/dayflower/boxnotes2md"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dayflower/boxnotes2md/releases/download/v0.1.3/boxnotes2md_Darwin_x86_64.tar.gz"
      sha256 "a8258891f7ba0f4c6284ec82d64c93d226f5d35dbadb51251c1c202180ea0718"

      def install
        bin.install "boxnotes2md"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dayflower/boxnotes2md/releases/download/v0.1.3/boxnotes2md_Darwin_arm64.tar.gz"
      sha256 "60162b4ca63cc845cf7b3f963946ac0d3079b18b8d6bf08eb3f177b9902865d9"

      def install
        bin.install "boxnotes2md"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dayflower/boxnotes2md/releases/download/v0.1.3/boxnotes2md_Linux_x86_64.tar.gz"
      sha256 "053b2133dd18335670dccd96668bfc6a818fbc03bb424863d02248d2b3443386"
      def install
        bin.install "boxnotes2md"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dayflower/boxnotes2md/releases/download/v0.1.3/boxnotes2md_Linux_arm64.tar.gz"
      sha256 "e88e465d2de0e14c5343920d4e551851183ace705e14b362f19c5671a9c86527"
      def install
        bin.install "boxnotes2md"
      end
    end
  end
end
