# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Boxnotes2md < Formula
  desc "Convert Box Notes JSON files into GitHub Flavored Markdown."
  homepage "https://github.com/dayflower/boxnotes2md"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dayflower/boxnotes2md/releases/download/v0.1.2/boxnotes2md_Darwin_x86_64.tar.gz"
      sha256 "0542af3f0ac96c418d627fd3adab85ee7762fc4eb91bfa5b1c39fb94f8252d60"

      def install
        bin.install "boxnotes2md"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dayflower/boxnotes2md/releases/download/v0.1.2/boxnotes2md_Darwin_arm64.tar.gz"
      sha256 "a13b27fc791f0eda82d21f05661d17cc6f8ea2341cf5a8710a258a6c8ec24b7e"

      def install
        bin.install "boxnotes2md"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dayflower/boxnotes2md/releases/download/v0.1.2/boxnotes2md_Linux_x86_64.tar.gz"
      sha256 "d36cf9c0e2510957f8bdba85fd90d7d1d1eda29fe8a280fcb6bcb04271d6cb6b"
      def install
        bin.install "boxnotes2md"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dayflower/boxnotes2md/releases/download/v0.1.2/boxnotes2md_Linux_arm64.tar.gz"
      sha256 "b9402f4476940384a7bef4eaafccba3f01881074e0ce00c12129e6218dbf77e1"
      def install
        bin.install "boxnotes2md"
      end
    end
  end
end
