# This file was generated by GoReleaser. DO NOT EDIT.
cask "boxnotes2md" do
  name "boxnotes2md"
  desc "Convert Box Notes JSON files into GitHub Flavored Markdown."
  homepage "https://github.com/dayflower/boxnotes2md"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "boxnotes2md"

  on_macos do
    on_intel do
      url "https://github.com/dayflower/boxnotes2md/releases/download/v#{version}/boxnotes2md_Darwin_x86_64.tar.gz"
      sha256 "2b63552f59d10b1be1994e55b4b6b03ba00107b677ed4fd7edd0f364f85de246"
    end
    on_arm do
      url "https://github.com/dayflower/boxnotes2md/releases/download/v#{version}/boxnotes2md_Darwin_arm64.tar.gz"
      sha256 "d56d2757582966eb4efc9980fc979baab6234992f3dfe37ff8012fe9d5f68f51"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dayflower/boxnotes2md/releases/download/v#{version}/boxnotes2md_Linux_x86_64.tar.gz"
      sha256 "1546c566709f7fe3ce750f108688ad0e01e8d7057453422905feba95afe6d8bd"
    end
    on_arm do
      url "https://github.com/dayflower/boxnotes2md/releases/download/v#{version}/boxnotes2md_Linux_arm64.tar.gz"
      sha256 "7a58c0391814f09324b0810e0a9b4e52afbfad334a1e291c29e8869a0638ec7f"
    end
  end

  # No zap stanza required
end
