# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ExportUaHistory < Formula
  desc "Chrome browsing history JSON export CLI"
  homepage "https://github.com/dayflower/export-ua-history"
  version "0.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dayflower/export-ua-history/releases/download/v0.0.4/export-ua-history_0.0.4_darwin_amd64.tar.gz"
      sha256 "1fb194556c6e99185cc21ef846cd8a920aa295242ef15f2cc21dee14bbec3579"

      define_method(:install) do
        bin.install "export-ua-history"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dayflower/export-ua-history/releases/download/v0.0.4/export-ua-history_0.0.4_darwin_arm64.tar.gz"
      sha256 "6d99154f43246f53fc2a0d8a45439b5a8b22c1941c8cd7290e1b1af25e54440f"

      define_method(:install) do
        bin.install "export-ua-history"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dayflower/export-ua-history/releases/download/v0.0.4/export-ua-history_0.0.4_linux_amd64.tar.gz"
      sha256 "8023ff50c4ccba4cf7c80b151faeaa47b0d8fcfb5b7b3913e74b3f43d2740402"
      define_method(:install) do
        bin.install "export-ua-history"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dayflower/export-ua-history/releases/download/v0.0.4/export-ua-history_0.0.4_linux_arm64.tar.gz"
      sha256 "62db5968e1af7555e56985bf3898242d0e905f3947b34aac200d52f3ff24ab45"
      define_method(:install) do
        bin.install "export-ua-history"
      end
    end
  end

  test do
    system "#{bin}/export-ua-history", "version"
  end
end
