# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MacWhisperExport < Formula
  desc "CLI tool to export meeting transcriptions from MacWhisper's database"
  homepage "https://github.com/dayflower/mac-whisper-export"
  version "0.1.1"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/dayflower/mac-whisper-export/releases/download/v0.1.1/mac-whisper-export_0.1.1_darwin_x86_64.tar.gz"
    sha256 "00e886f96555459226d3c8e3bad206ca544e0d5b921bd606bcfa8dc1840c7f66"

    def install
      bin.install "mac-whisper-export"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/dayflower/mac-whisper-export/releases/download/v0.1.1/mac-whisper-export_0.1.1_darwin_arm64.tar.gz"
    sha256 "05f157fab1bb0fd01c924c20f79b57bc90b46d7a6e6fed8116b95c546bb93fc6"

    def install
      bin.install "mac-whisper-export"
    end
  end
end
