# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xcute < Formula
  desc "A CLI tool that executes commands with placeholders replaced by input from stdin"
  homepage "https://github.com/dayflower/xcute"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dayflower/xcute/releases/download/v0.1.1/xcute_Darwin_x86_64.tar.gz"
      sha256 "268a8a0782a60c0f093cc3c08f80d62cb4e3e3e7daa866ffba14339456970060"

      def install
        bin.install "xcute"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dayflower/xcute/releases/download/v0.1.1/xcute_Darwin_arm64.tar.gz"
      sha256 "e34b22f5fed21d1781b1f6834f5f0bbee67c38a90b77843e0a4bcef6b00e7fc9"

      def install
        bin.install "xcute"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dayflower/xcute/releases/download/v0.1.1/xcute_Linux_x86_64.tar.gz"
      sha256 "b66256f3a5aa974682f05dde965e314d47f03cdbb092922b4053bd9f3546163f"
      def install
        bin.install "xcute"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dayflower/xcute/releases/download/v0.1.1/xcute_Linux_arm64.tar.gz"
      sha256 "28f6032d6e5318b2877ef2e9224c33db14de95d0893dc8003761b66711e45c2e"
      def install
        bin.install "xcute"
      end
    end
  end

  test do
    system "#{bin}/xcute", "--help"
  end
end
